### ISSUE TITLE
If I have both wx3.0 and wx3.1 installed in the msys2, it looks like this tool will use wx3.1

### ISSUE THREAD

**Issue by asmwarrior** [eranif/wx-config-msys2#1]
Hi, eranif, thanks for the good tool!

I'm not sure if it could have an option for me to select the wx version? For me, both wx 3.1 and wx 3.0 libraries in my msys2's mingw-w64 suite.

Thanks

**Comment by eranif** [comment]
How would you suggest to fix this?
I am thinking of `--use-version` switch or something like that

**Comment by eranif** [comment]
Actually, I am just looking at the code and I remembered that I added an option to pass `WXVER` environment variable
Something like:

`WXVER=3.0 ./wx-config-msys2 --libs --prefix=C:\msys64\mingw64`

**Comment by eranif** [comment]
I just tried that:

```bash
Eran@windows-10 MSYS /c/src/wx-config-msys2/build-release
$ WXVER=3.0 ../bin/wx-config-msys2.exe --libs=std,adv --prefix="C:\msys64\mingw64"
-LC:\msys64\mingw64\lib -pipe -Wl,--subsystem,windows -mwindows -lwx_mswu_xrc-3.0 -lwx_mswu_html-3.0 -lwx_mswu_qa-3.0 -lwx_mswu_core-3.0 -lwx_baseu_xml-3.0 -lwx_baseu_net-3.0 -lwx_baseu-3.0 -lwx_mswu_adv-3.0


```

**Comment by asmwarrior** [comment]
OK, thanks for your explanation.
