### ISSUE TITLE
add lib option "media"

### ISSUE THREAD

**Issue by asmwarrior** [eranif/wx-config-msys2#11]
Hi, when trying to build the splash wx sample code.

See my wx sample projects using `wx-config-msys2.exe` and code::blocks
https://github.com/asmwarrior/cb_projects_for_wxWidgets

I try to use this linker option:

~~~~
`$(#WX_CONFIG) --libs std,media`
~~~~

But this does not include the necessary media library, so I have to manually add a library name to linker option to workaround this:

~~~~
`$(#WX_CONFIG) --libs std,media`
-lwx_mswu_media-3.2
~~~~

So, can you have this "media" keyword support? Thanks.

**Comment by eranif** [comment]
FYI: I can't see `libwx_mswu_media` in the list of files installed on my MinGW env (wx3.0)
when switching to `3.2` I can see it
