### ISSUE TITLE
I suggest do not generate the -O2 like option

### ISSUE THREAD

**Issue by asmwarrior** [eranif/wx-config-msys2#5]
Hi, eranif.

If I use the command

`wx-config-msys2 --cflags --prefix=$(TARGET_COMPILER_DIR) --debug`

I got the `-O0` option, if no `--debug` is specified, I got the `-O2` option.

While, I just compared with other tools, such as the `pkg-config` under msys2

```
# pkg-config --cflags opencv4
-IF:/msys2/mingw64/include/opencv4
```

It does not generate the `-O` like options.  The issue here is that I have already configured the '-O` like option in other field inside the Code::Blocks' build options.

What do you think about this issue, thanks.

**Comment by eranif** [comment]
sounds reasonable to remove it.
I see that the Ubuntu's `wx-config` does not add it as well (neither the `-DNDEBUG`)

**Comment by asmwarrior** [comment]
I found some new information under msys2.
I just looked at the file:  
```
# which wx-config
/mingw64/bin/wx-config
```
This is a script file, and if you search the "debug" keyword, you see some text mention this option:

>   NOTE:    Usage of --debug and --query-debugtype are only relevant if you
>   have any  versions prior to 2.9 installed  and use the --version option to
>   select an earlier version.

and

>  Input options that accept only a yes or no argument.
> 
> Notice that this includes "debug" but it is done only for compatibility, this
> options (i.e. --debug[=yes] or --debug=no) is completely ignored as there is
> no distinction between debug and release builds in wx any more

**Comment by asmwarrior** [comment]
Hi, I just check the latest revision, and it looks like you already fix this issue. Thanks. 

I see you also removed the `-mwindows` option, that's great! If this option is on, under CodeBlocks, if I set the build target as console application, then the result application always don't have a console window. That's a bit annoying. Luckily you fix it. Thanks.

BTW: I see now you have two target. One is `wx-config-msys2`, the other is `wx-config`. Can you add some example about the usage of `wx-config`. I see you have one commit message said:

> wx-config.exe supports wxWidgets built using CMake with different compilers (clang, gcc etc), tested and verified on MSYS2 shell

So, maybe an example about how to use it under CMake?

For me, to use CMake(The one from /mingw64/bin/cmake), I have to hack the `FindwxWidgets.cmake`, see this post of mine: [Re: Using wxWidgets with Win10, msys2, mingw64 and CLion](https://forums.wxwidgets.org/viewtopic.php?p=202984&sid=d9fd103405fee5feb96378064e7810c3#p202984)

**Comment by eranif** [comment]
there are 2 common ways to build and install wxWidgets on Windows, each uses different installation layout:
- If you choose to install wxWidgets using `MSYS2` (e.g. by using `pacman -S mingw-w64-x86_64-wxWidgets`), then you should use `wx-config-msys2.exe` 
- If you choose to build wxWidgets yourself, using `CMake` (as described here: https://docs.codelite.org/build/build_wx_widgets/) - then you should use `wx-config.exe`

**Comment by asmwarrior** [comment]
> there are 2 common ways to build and install wxWidgets on Windows, each uses different installation layout:
> 
>     * If you choose to install wxWidgets using `MSYS2` (e.g. by using `pacman -S mingw-w64-x86_64-wxWidgets`), then you should use `wx-config-msys2.exe`
> 
>     * If you choose to build wxWidgets yourself, using `CMake` (as described here: https://docs.codelite.org/build/build_wx_widgets/#windows) - then you should use `wx-config.exe`

Thanks for the explanation.

**Comment by eranif** [comment]
Done
