### ISSUE TITLE
Can't get past the build step

### ISSUE THREAD

**Issue by ga2k** [eranif/wx-config-msys2#6]
Hi, I'm trying to build this without much luck. It's probably a configuration problem, but when I follow along step by step, this is the result at the make step...
```
geoffrey@Grunter MSYS /d/dev/repos/wx-config-msys2/build-release
$ mingw32-make -j24
[ 50%] Building CXX object src/CMakeFiles/wx-config-msys2.dir/wx-config-msys2.cpp.o
D:\Dev\Repos\wx-config-msys2\src\wx-config-msys2.cpp:1:10: fatal error: 'filesystem' file not found
#include <filesystem>
         ^~~~~~~~~~~~
1 error generated.
mingw32-make[2]: *** [src\CMakeFiles\wx-config-msys2.dir\build.make:75: src/CMakeFiles/wx-config-msys2.dir/wx-config-msys2.cpp.o] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:97: src/CMakeFiles/wx-config-msys2.dir/all] Error 2
mingw32-make: *** [Makefile:90: all] Error 2
```
Any advice?

**Comment by asmwarrior** [comment]
[build this tool under the mingw-w64 shell · Issue #3 · eranif/wx-config-msys2](https://github.com/eranif/wx-config-msys2/issues/3)

I don't have this issue, see the above issue.

Make sure you are using the 64bit mingw shell, not the msys shell.

**Comment by eranif** [comment]
You will need a `C++20` compiler.
Follow this instructions as described here: https://docs.codelite.org/build/mingw_builds/
