### ISSUE TITLE
Fails to list "-lwx_mswu_stc-3.0" in library list

### ISSUE THREAD

**Issue by stahta01** [eranif/wx-config-msys2#7]
wx-config-msys2.exe --prefix=C:/msys64/mingw64  --libs std,stc

Fails to list "-lwx_mswu_stc-3.0" in library list

Tim S.

`./wx-config-msys2.exe --prefix=C:/msys64/mingw64  --libs std,stc
-LC:/msys64/mingw64\lib -pipe -Wl,--subsystem,windows -mwindows -lwx_mswu_xrc-3.0 -lwx_mswu_html-3.0 -lwx_mswu_qa-3.0 -lwx_mswu_core-3.0 -lwx_baseu_xml-3.0 -lwx_baseu_net-3.0 -lwx_baseu-3.0`

As compared to

`wx-config --libs std,stc
-LC:/msys64/mingw64/lib   -pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high -Wl,--subsystem,windows -mwindows -lwx_mswu_stc-3.0 -lwx_mswu_xrc-3.0 -lwx_mswu_webview-3.0 -lwx_mswu_html-3.0 -lwx_mswu_qa-3.0 -lwx_mswu_adv-3.0 -lwx_mswu_core-3.0 -lwx_baseu_xml-3.0 -lwx_baseu_net-3.0 -lwx_baseu-3.0`

**Comment by asmwarrior** [comment]
Hi, @stahta01 

You can see this comment here:

https://github.com/eranif/wx-config-msys2/issues/8#issuecomment-1074312849

It does have the "-lwx_mswu_stc-3.0" for the latest git head, can you confirm it?

**Comment by eranif** [comment]
I checked this locally and it works as expected
